const errorCodes = {
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  FAIL_TO_CHANGE_PASSWORD: 'FAIL_TO_CHANGE_PASSWORD',
  FAIL_TO_SEND_PASSWORD_RECOVERY_EMAIL: 'FAIL_TO_SEND_PASSWORD_RECOVERY_EMAIL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
};

export default errorCodes;
