const errorCodes = {
  FAILED_TO_CANCEL_SUBSCRIPTION: 'FAILED_TO_CANCEL_SUBSCRIPTION',
  FAILED_TO_CREATE_PAYMENT_INTENT: 'FAILED_TO_CREATE_PAYMENT_INTENT',
  FAILED_TO_CREATE_SUBSCRIPTION: 'FAILED_TO_CREATE_SUBSCRIPTION',
  INVALID_COUPON_CODE: 'INVALID_COUPON_CODE',
  USER_ALREADY_HAS_SAME_SUBSCRIPTION: 'USER_ALREADY_HAS_SAME_SUBSCRIPTION',
};

export default errorCodes;
